# Generated by Django 5.1.5 on 2025-01-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=19)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('cost', models.DecimalField(decimal_places=10, max_digits=19)),
                ('size', models.DecimalField(decimal_places=10, max_digits=19)),
                ('description', models.CharField(max_length=255)),
                ('age_limited', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
